apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rdicidr-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: fsl-challenge.me
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rdicidr-service
                port:
                  number: 80
